---
# This playbook will install MariaDB and create db user and give permissions.

- name: MariaDB repository definition
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: Install MariaDB package
  package:
    name:
      - epel-release
      - mariadb-server
      - MySQL-python
      - libsemanage-python
    state: latest

- name: Create MariaDB log file
  file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0775
    modification_time: preserve
    access_time: preserve

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- block:
    - name: Copy database dump file
      copy:
          src: "{{ db_import_file }}"
          dest: /tmp/backup.sql

    - name: Import {{ db_name }} database
      mysql_db:
          name: "{{ db_name }}"
          state: "import"
          target: /tmp/backup.sql
  when: db_import_file | length > 0

- name: Create {{ db_name }} database
  mysql_db:
    name: "{{ db_name }}"
    state: present
  when: db_import_file | length == 0

- name: Create {{ db_user.name }} database user
  mysql_user:
    name: "{{ db_user.name }}"
    host: "{{ db_user.host }}"
    password: "{{ db_user.password }}"
    priv: "{{ db_user.name }}.*:ALL"
    state: present

- name: Ensure password-less access for root
  mysql_user:
    name: root
    host: "localhost"
    password: ""
    state: present
