---

- name: NGINX repository definition
  yum_repository:
    name: nginx
    description: Nginx repo - $basearch
    baseurl: http://nginx.org/packages/centos/7/$basearch
    gpgcheck: no

- name: Install nginx
  package: name=nginx state=present

- name: Copy nginx server configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: http service state
  service: name=nginx state=started enabled=yes
