---
- name: Install wordpress
  unarchive:
    src: "{{ wp_archive }}"
    dest: "{{ wp_server_root }}"
    creates: "{{ wp_server_root }}/wordpress/index.php"
    owner: wordpress
    remote_src: yes

- name: Copy WordPress config file
  template: src=wp-config.php dest={{ wp_server_root }}/wordpress owner=wordpress
