---

- name: Make slave read_only
  ini_file:
    dest: /etc/my.cnf
    section: mysqld
    option: read_only
    allow_no_value: true
  notify: restart mariadb

- name: Make slave binlog-do-db
  ini_file:
    dest: /etc/my.cnf
    section: mysqld
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - option: replicate-do-db
      value: "{{ db_name }}"
    - option: server-id
      value: "{{ mysql_server_id}}"
  notify: restart mariadb

- meta: flush_handlers

- name: Check slave replication status.
  mysql_replication:
    mode: getslave
  ignore_errors: true
  register: slave

- name: Check master replication status.
  mysql_replication: 
    mode: getmaster
  delegate_to: "donald"
  register: master
  when:
    - slave.Is_Slave is defined and not slave.Is_Slave

- name: Configure replication on the slave.
  mysql_replication:
    mode: changemaster
    master_host: "{{ hostvars[mysql_replication_master].ansible_default_ipv4.address }}"
    master_user: "replication"
    master_password: "replication"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  when:
    - slave.Is_Slave is defined and not slave.Is_Slave

- name: Start replication.
  mysql_replication: 
    mode: startslave
  when:
    - slave.Is_Slave is defined and not slave.Is_Slave
